services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://${USER_USER}:${USER_PASSWORD}@user-db:5432/${USER_DB}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - user-db

  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${USER_USER}
      POSTGRES_PASSWORD: ${USER_PASSWORD}
    volumes:
      - user_data:/var/lib/postgresql/data
      - ./user-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  reservation-service:
    build: ./reservation-service
    ports:
      - "5003:5000"
    environment:
      DATABASE_URL: postgresql://${RESERVATION_USER}:${RESERVATION_PASSWORD}@reservation-db:5432/${RESERVATION_DB}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - reservation-db

  reservation-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${RESERVATION_DB}
      POSTGRES_USER: ${RESERVATION_USER}
      POSTGRES_PASSWORD: ${RESERVATION_PASSWORD}
    volumes:
      - reservation_data:/var/lib/postgresql/data
      - ./reservation-service/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  user_data:
  reservation_data: