sonar.projectKey=architecture-si-project_devOps-loc
sonar.organization=efrei-devops-rent

sonar.python.version=3.13
sonar.python.coverage.reportPaths=user-service/coverage.xml,reservation-service/coverage.xml

sonar.sources=user-service/user_app,user-service/main.py,reservation-service/main.py,reservation-service/reservation_app
sonar.tests=user-service/tests,reservation-service/tests
sonar.exclusions=**/tests/**,**/__pycache__/**
sonar.cpd.exclusions=**/decorators.py
